services:
  # API
  api:
    build: ./api
    networks:
      - frontend
      - backend
    environment:
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASS=password
    volumes:
      - logs_volume:/app/logs
    depends_on:
      - db
    read_only: true # Sécurité système fichiers

  # BASE DE DONNEES
  db:
    image: postgres:13-alpine
    networks:
      - backend # Isolé du frontend
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  # REVERSE PROXY
  reverse:
    image: nginx:alpine
    networks:
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  # MONITORING
  monitor:
    build: ./monitor
    volumes:
      - logs_volume:/logs:ro # Lecture seule

volumes:
  db_data:
  logs_volume:

networks:
  frontend:
  backend:
    internal: true # Pas d'accès internet pour la DB
